stages:
  - build
variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.12-dind

build:
  image:
    name: docker:19.03.12-dind
    entrypoint: [""]

  stage: build
  tags:
    - docker-build
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}/glvar:latest" .
    - docker login -u $DOCKER_LOGIN $DOCKER_PASSWORD
    - docker push "${CI_REGISTRY_IMAGE}/glvar:latest"
