stages:
  - build

services:
  - docker:19.03.12-dind

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t "${CI_REGISTRY_IMAGE}/glvar:latest" .
    - docker push "${CI_REGISTRY_IMAGE}/glvar:latest"
